# Generated by Django 4.0.4 on 2022-05-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(null=True),
        ),
    ]
